function(add_arl_executable name)
    add_executable(${name} ${ARGN})
    target_link_libraries(${name} PRIVATE arl)
    set_target_properties(${name} PROPERTIES OUTPUT_NAME "arl_${name}")
    install(TARGETS ${name} RUNTIME)
endfunction()

function(add_gex_executable name)
    if(TARGET PkgConfig::gasnet)
        add_executable(${name} ${ARGN})
        target_link_libraries(${name} PRIVATE PkgConfig::gasnet)
        if (ARL_USE_GASNET_NEED_MPI)
            target_link_libraries(${name} PRIVATE MPI::MPI_CXX)
        endif()
        target_link_libraries(${name} PRIVATE arl)
        set_target_properties(${name} PROPERTIES OUTPUT_NAME "arl_${name}")
        install(TARGETS ${name} RUNTIME)
    endif()
endfunction()

function(add_upcxx_executable name)
    if(TARGET UPCXX::upcxx)
        add_executable(${name} ${ARGN})
        if (ARL_USE_GASNET_NEED_MPI)
            target_link_libraries(${name} PRIVATE MPI::MPI_CXX)
        endif()
        target_link_libraries(${name} PRIVATE UPCXX::upcxx)
        set_target_properties(${name} PROPERTIES OUTPUT_NAME "arl_${name}")
        install(TARGETS ${name} RUNTIME)
    endif()
endfunction()