function(add_arl_executable EXEC)
    add_executable(${EXEC} ${ARGN})
    target_link_libraries(${EXEC} PRIVATE arl)
endfunction()

function(add_gex_executable EXEC)
    add_executable(${EXEC} ${ARGN})
    target_link_libraries(${EXEC} PRIVATE PkgConfig::gasnet)
    target_link_libraries(${EXEC} PRIVATE MPI::MPI_CXX)
    target_link_libraries(${EXEC} PRIVATE arl)
endfunction()

function(add_upcxx_executable EXEC)
    if (TARGET UPCXX::upcxx)
        add_executable(${EXEC} ${ARGN})
        target_link_libraries(${EXEC} PRIVATE MPI::MPI_CXX)
        target_link_libraries(${EXEC} PRIVATE UPCXX::upcxx)
    else()
        message(WARNING "UPCXX::upcxx target not found. ${EXEC} will not be built.")
    endif()
endfunction()