# Acknowledgement:
#   Most content in this file is based on the source code of
#   the Berkeley Container Library (https://github.com/berkeley-container-library/bcl).
#

install:

language: c++

services:
  - docker

compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libopenmpi-dev
            - openmpi-bin
            - wget

before_install:
  - docker pull benbrock/bcl:mpich-debug
  - eval "${MATRIX_EVAL}"

script:
  - docker run --name container -u ubuntu -w /home/ubuntu -v $(pwd):/home/ubuntu/host-arl -d -it --shm-size=2048M -d benbrock/bcl:mpich-debug # keep container alive
  - docker exec --user root container bash -c "chown -R ubuntu:ubuntu /home/ubuntu/host-arl"
  - docker exec --user ubuntu container bash -c "cd ./host-arl/tests/ && ./run_tests.sh gasnet_ex" # run the test script
