# Acknowledgement:
#   Most content in this file is based on the source code of
#   the Berkeley Container Library (https://github.com/berkeley-container-library/bcl).
#

install:

language: c++

services:
  - docker

compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libopenmpi-dev
            - openmpi-bin
            - wget

before_install:
  - docker pull jiakuny/arl-testbed:latest
  - eval "${MATRIX_EVAL}"

script:
  - docker run --name arl-testbed -w /root -v $(pwd):/root/host -d -it --shm-size=2048M -d jiakuny/arl-testbed:latest # keep container alive
  - docker exec --user root arl-testbed bash -c "cd ./host/ && mkdir build && cd build && cmake .. && make && ctest --timeout 30 --verbose"
